format = """
[░▒▓](#30281d)\
[  ](bg:#30281d fg:#f2c993)\
$directory\
[](fg:#30281d bg:#483c2c)\
[](fg:#483c2c bg:#60503a)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#60503a bg:#796449)\
$time\
[ ](fg:#796449)\
\n$character"""

[directory]
style = "fg:#f3c993 bg:#30281d"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

#[git_branch]
#symbol = ""
#style = "bg:#394260"
#format = '[[($symbol $brach )](fg:#769ff0 bg:#394260)]($style)'

#[git_status]
#style = "bg:#394260"
#format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
symbol = ""
style = "bg:#30281d"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#30281d"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#30281d"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#30281d"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#f2c993 bg:#30281d)]($style)'

